# Generated by Django 3.2.4 on 2021-06-10 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_auto_20210610_0926'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CashAndInvestments', models.IntegerField(null=True)),
                ('TotalAssets', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FinancialSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PremiumIncome', models.IntegerField()),
                ('OtherIncome', models.IntegerField()),
                ('InvestmentIncome', models.IntegerField()),
                ('Credits', models.IntegerField()),
                ('Expenses', models.IntegerField()),
                ('NetIncome', models.IntegerField()),
                ('Year', models.PositiveIntegerField()),
            ],
        ),
    ]
