# Generated by Django 3.2.4 on 2021-06-10 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_financialposition_financialsummary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialsummary',
            name='Year',
            field=models.PositiveIntegerField(unique=True),
        ),
    ]
