# Generated by Django 3.2.4 on 2021-06-10 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_financialsummary_year'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FinancialPosition',
        ),
    ]
